# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x07\x64\x65vices\"C\n\x0e\x43ommandRequest\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x05\"5\n\x0c\x43ommandReply\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t2K\n\x0cManageDevice\x12;\n\x07\x63ommand\x12\x17.devices.CommandRequest\x1a\x15.devices.CommandReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=25
  _globals['_COMMANDREQUEST']._serialized_end=92
  _globals['_COMMANDREPLY']._serialized_start=94
  _globals['_COMMANDREPLY']._serialized_end=147
  _globals['_MANAGEDEVICE']._serialized_start=149
  _globals['_MANAGEDEVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
